# Generated by Django 5.1.6 on 2025-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=32)),
                ('emp_location', models.CharField(max_length=32)),
                ('emp_phone', models.CharField(max_length=16)),
            ],
        ),
    ]
