# Generated by Django 5.1.6 on 2025-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0002_alter_employeeinfo_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_phone',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
