# Generated by Django 5.1.6 on 2025-02-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0003_alter_employeeinfo_emp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_locations', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='Employee_Note.locations'),
        ),
    ]
