# Generated by Django 5.1.6 on 2025-02-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0005_phonenumbers_alter_employeeinfo_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_phone',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='mobile_numbers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee_Note.employeeinfo'),
        ),
    ]
