# Generated by Django 5.1.6 on 2025-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0006_alter_employeeinfo_emp_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
