# Generated by Django 5.1.6 on 2025-02-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0007_phonenumbers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='emp_phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
