# Generated by Django 5.1.6 on 2025-02-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0008_alter_employeeinfo_emp_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='mobile_numbers',
            new_name='employee_data',
        ),
    ]
