# Generated by Django 5.1.6 on 2025-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
