# Generated by Django 5.1.6 on 2025-02-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0011_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='Ready', max_length=16),
        ),
    ]
