# Generated by Django 5.1.6 on 2025-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0013_report_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_numbers',
            field=models.CharField(max_length=255),
        ),
    ]
