# Generated by Django 5.1.6 on 2025-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0014_alter_report_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
