# Generated by Django 5.1.6 on 2025-03-10 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0015_alter_report_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='phone_numbers',
        ),
    ]
