# Generated by Django 5.1.6 on 2025-03-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0016_remove_report_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_phone_numbers', models.CharField(default=None, max_length=10, unique=True)),
                ('note_delivery_time', models.DateTimeField()),
                ('note_status', models.CharField(max_length=10)),
                ('related_campaign',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee_Note.report')),
            ],
        ),
    ]
