# Generated by Django 5.1.6 on 2025-03-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0017_reportphonenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default=None, max_length=32, unique=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('total_count_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('note_description', models.CharField(default=None, max_length=2048)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(default='Ready', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportphonenumbers',
            name='related_campaign',
        ),
        migrations.CreateModel(
            name='CampaignDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_phone_numbers', models.CharField(default=None, max_length=10, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=10, unique=True)),
                ('delivery_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('note_status', models.CharField(default='ready', max_length=10)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='Employee_Note.campaign')),
                ('employee_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    to='Employee_Note.employeeinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportPhoneNumbers',
        ),
    ]
