# Generated by Django 5.1.6 on 2025-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0018_campaign_remove_reportphonenumbers_related_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='phone_numbers_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
