# Generated by Django 5.1.6 on 2025-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0019_campaign_phone_numbers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndetails',
            name='delivery_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
