# Generated by Django 5.1.6 on 2025-03-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0020_alter_campaigndetails_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndetails',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
