# Generated by Django 5.1.6 on 2025-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0021_alter_campaigndetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndetails',
            name='masked_phone_numbers',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
