# Generated by Django 5.1.6 on 2025-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Employee_Note', '0022_alter_campaigndetails_masked_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndetails',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
    ]
