# Generated by Django 5.1.6 on 2025-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Note', '0023_alter_campaigndetails_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='total_count_of_employees',
            new_name='total_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='phone_numbers_id',
        ),
        migrations.AlterField(
            model_name='campaigndetails',
            name='delivery_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
